export const enum SYMBOL {
    EMPTY = 0,
    BAR = 1,
    BARX2 = 2,
    SEVEN = 3,
    CHERRY = 4,
    BARX3 = 5
}

export const REELS = [
    [SYMBOL.BAR, SYMBOL.EMPTY, SYMBOL.BARX2, SYMBOL.EMPTY, SYMBOL.SEVEN, SYMBOL.EMPTY, SYMBOL.CHERRY, SYMBOL.EMPTY, SYMBOL.BARX3, SYMBOL.EMPTY],
    [SYMBOL.BAR, SYMBOL.EMPTY, SYMBOL.BARX2, SYMBOL.EMPTY, SYMBOL.SEVEN, SYMBOL.EMPTY, SYMBOL.CHERRY, SYMBOL.EMPTY, SYMBOL.BARX3, SYMBOL.EMPTY],
    [SYMBOL.BAR, SYMBOL.EMPTY, SYMBOL.BARX2, SYMBOL.EMPTY, SYMBOL.SEVEN, SYMBOL.EMPTY, SYMBOL.CHERRY, SYMBOL.EMPTY, SYMBOL.BARX3, SYMBOL.EMPTY]
]

export const PAYLINES = [
    [0,0,0],
    [1,1,1],
    [2,2,2]
]

export const PAYOUTS = [
    [2000, 150, 75, 50, 20, 10, 5],
    [1000, 150, 75, 50, 20, 10, 5],
    [4000, 150, 75, 50, 20, 10, 5]
]